version: "3.1"
services:
  nginx:
    restart: always #docker 启动这个容器也跟着启动
    image: code-lives-php:7.4
    container_name: location #容器的名称
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD:/var/www/html